FROM ubuntu:20.04

RUN apt-get -qq update \
    && DEBIAN_FRONTEND=noninteractive apt-get -qq -y install \
        apt-transport-https \
        autoconf \
        build-essential \
        cmake \
        curl \
        jq \
        debhelper \
        default-jre-headless \
        devscripts \
        dh-autoreconf \
        git \
        libgmp-dev \
        libsodium-dev \
        libssl-dev \
        ncurses-dev \
        unzip \
        libwxbase3.0-dev \
        libwxgtk3.0-gtk3-dev \
        libsctp1 \
        libgflags-dev \
        libsnappy-dev \
        zlib1g-dev \
        libbz2-dev \
        liblz4-dev \
        libzstd-dev \
        libncurses5 \
    && rm -rf /var/lib/apt/lists/*

ARG BUILD_OTP_VERSION="22.3.4.9"
ENV OTP_VERSION=$BUILD_OTP_VERSION
RUN PACKAGE_NAME=esl-erlang_${OTP_VERSION}-1~ubuntu~focal_$(dpkg --print-architecture).deb \
    && OTP_DOWNLOAD_URL=https://packages.erlang-solutions.com/erlang/debian/pool/${PACKAGE_NAME} \
    && curl -fsSL -o ${PACKAGE_NAME} "$OTP_DOWNLOAD_URL" \
    && dpkg -i ${PACKAGE_NAME} \
    && rm esl-erlang_${OTP_VERSION}-1~ubuntu~focal_$(dpkg --print-architecture).deb

ENV ROCKSDB_VERSION=6.13.3
RUN set -xe \
    && ROCKSDB_DOWNLOAD_URL="https://github.com/facebook/rocksdb/archive/v${ROCKSDB_VERSION}.tar.gz" \
    && ROCKSDB_DOWNLOAD_SHA256="b86741983c5842716128efc2eecc1a2f3bc86ba5125cf3111fb58d26fb195ff0" \
    && curl -fsSL -o rocksdb-src.tar.gz "$ROCKSDB_DOWNLOAD_URL" \
    && echo "$ROCKSDB_DOWNLOAD_SHA256 rocksdb-src.tar.gz" | sha256sum -c - \
    && mkdir rocksdb-src \
    && tar -zxf rocksdb-src.tar.gz -C rocksdb-src --strip-components=1 \
    && cd rocksdb-src \
    && PORTABLE=1 make shared_lib && make install-shared && ldconfig

ENV REBAR3_VERSION="3.17.0"
RUN set -xe \
    && REBAR3_DOWNLOAD_URL="https://github.com/erlang/rebar3/archive/${REBAR3_VERSION}.tar.gz" \
    && REBAR3_DOWNLOAD_SHA256="4c7f33a342bcab498f9bf53cc0ee5b698d9598b8fa9ef6a14bcdf44d21945c27" \
    && mkdir -p /usr/src/rebar3-src \
    && curl -fSL -o rebar3-src.tar.gz "$REBAR3_DOWNLOAD_URL" \
    && echo "$REBAR3_DOWNLOAD_SHA256 rebar3-src.tar.gz" | sha256sum -c - \
    && tar -xzf rebar3-src.tar.gz -C /usr/src/rebar3-src --strip-components=1 \
    && rm rebar3-src.tar.gz \
    && cd /usr/src/rebar3-src \
    && HOME=$PWD ./bootstrap \
    && install -v ./rebar3 /usr/local/bin/ \
    && rm -rf /usr/src/rebar3-src

# Add non-root user in case some app won't run as root
RUN useradd --shell /bin/bash builder --create-home

ENV SHELL=/bin/bash
