version: 2.1

references:
  container_config: &container_config
    docker:
      - image: golang:1.8.0
    working_directory: ~/builder
    environment:
      DOCKERHUB_REPO: aeternity/builder
      DOCKER_CLIENT_VERSION: "17.09.0-ce"
      DOCKERFILE_PATH: "."

  setup_remote_docker: &setup_remote_docker
    setup_remote_docker:
      docker_layer_caching: true
      version: "17.09.0-ce"

  install_docker_client: &install_docker_client
    run:
      name: Install Docker client
      command: |
        curl -L -o /tmp/docker-${DOCKER_CLIENT_VERSION:?}.tgz \
          https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_CLIENT_VERSION:?}.tgz
        tar -xz -C /tmp -f /tmp/docker-${DOCKER_CLIENT_VERSION:?}.tgz
        mv /tmp/docker/* /usr/bin

  build_and_push: &build_and_push
    run:
      name: Build and push Docker image
      command: |
        docker build -t $DOCKERHUB_REPO:$TAG \
          --build-arg BUILD_OTP_VERSION=${BUILD_OTP_VERSION:-20.3.8.9} $DOCKERFILE_PATH
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker push $DOCKERHUB_REPO:$TAG

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - *setup_remote_docker
      - *install_docker_client
      - run:
          name: Configure docker image tag
          command: |
            echo "export TAG=ci-build-$CIRCLE_BRANCH" >> $BASH_ENV
      - *build_and_push

  build_1604_otp21:
    <<: *container_config
    steps:
      - checkout
      - *setup_remote_docker
      - *install_docker_client
      - run:
          name: Configure docker image tag
          command: |
            echo "export TAG=otp21" >> $BASH_ENV
            echo "export BUILD_OTP_VERSION=21.3.8.6" >> $BASH_ENV
      - *build_and_push

  build_1804:
    <<: *container_config
    steps:
      - checkout
      - *setup_remote_docker
      - *install_docker_client
      - run:
          name: Configure docker image tag
          command: |
            echo "export TAG=1804" >> $BASH_ENV
            echo "export DOCKERFILE_PATH=package_ubuntu_18.04" >> $BASH_ENV
      - *build_and_push

  deploy:
    <<: *container_config
    steps:
      - checkout
      - *setup_remote_docker
      - *install_docker_client
      - run:
          name: Configure docker image tag
          command: |
            echo "export TAG=latest" >> $BASH_ENV
      - *build_and_push

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master

      - build_1804:
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_1604_otp21:
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - deploy:
          context: ae-dockerhub
          filters:
            branches:
              only: master
