version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable-18.04
    working_directory: ~/builder
    environment:
      DOCKERHUB_REPO: aeternity/builder
      DOCKER_CLIENT_VERSION: "20.10.11"
      DOCKERFILE_PATH: "."

commands:
  use_remote_docker:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: "20.10.11"
  build_and_push:
    parameters:
      dockerfile:
        type: string
      otp_version:
        type: string
      tag:
        type: string
      latest:
        type: boolean
        default: false
    steps:
      - run:
          name: Setup buildx
          command: |
            docker context create aeternity
            docker buildx create --use --platform linux/amd64,linux/arm64 aeternity
      - run:
          name: Build Docker image
          environment:
            DOCKER_CLI_EXPERIMENTAL: enabled
          command: |
            docker buildx build --progress=plain -t $DOCKERHUB_REPO:<< parameters.tag >> \
              --platform linux/amd64,linux/arm64 \
              --build-arg BUILD_OTP_VERSION=<< parameters.otp_version >> - < << parameters.dockerfile >>
      - run:
          name: Push Docker image to docker.io registry
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKERHUB_REPO:<< parameters.tag >>
      - when:
          condition: << parameters.latest >>
          steps:
            - run:
                name: Tag and push latest
                command: |
                  docker tag $DOCKERHUB_REPO:<< parameters.tag >> $DOCKERHUB_REPO:latest
                  docker push $DOCKERHUB_REPO:latest

jobs:
  build_and_push:
    executor: base
    parameters:
      distro:
        type: string
      otp_version:
        type: string
      tag:
        type: string
        default: bionic-otp22
      latest:
        type: boolean
        default: false
    steps:
      - checkout
      - use_remote_docker
      - build_and_push:
          dockerfile: Dockerfile-<< parameters.distro >>
          otp_version: << parameters.otp_version >>
          tag: << parameters.tag >>
          latest: << parameters.latest >>

workflows:
  version: 2
  commit:
    jobs:
      - build_and_push:
          name: "build_1804_otp22"
          distro: "bionic"
          otp_version: "22.3.4.9"
          tag: ci-bionic-otp22-<< pipeline.git.branch >>
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master
      - build_and_push:
          name: "build_2004_otp22"
          distro: "focal"
          otp_version: "22.3.4.9"
          tag: ci-focal-otp22-<< pipeline.git.branch >>
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master

  release:
    jobs:
      - build_and_push:
          name: "build_1804_otp22"
          distro: "bionic"
          otp_version: "22.3.4.9"
          tag: "bionic-otp22"
          latest: true
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_1804_otp23"
          distro: "bionic"
          otp_version: "23.3.4.5"
          tag: "bionic-otp23"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_1804_otp24"
          distro: "bionic"
          otp_version: "24.1.3"
          tag: "bionic-otp24"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_2004_otp22"
          distro: "focal"
          otp_version: "22.3.4.9"
          tag: "focal-otp22"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_2004_otp23"
          distro: "focal"
          otp_version: "23.3.4.5"
          tag: "focal-otp23"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_2004_otp24"
          distro: "focal"
          otp_version: "24.1.3"
          tag: "focal-otp24"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master
