version: 2.1

parameters:
  docker_repo:
    type: string
    default: aeternity/builder
  otp24:
    type: string
    default: "24.3.3.1"
  otp25:
    type: string
    default: "25.3.2"
  otp26:
    type: string
    default: "26.2.1"

executors:
  amd64:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: xlarge
  arm64:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: arm.xlarge

commands:
  build_and_push:
    parameters:
      dockerfile:
        type: string
      otp_version:
        type: string
      tag:
        type: string
      latest:
        type: boolean
        default: false
    steps:
      - run:
          name: Build Docker image
          command: |
            docker build -t << pipeline.parameters.docker_repo >>:<< parameters.tag >> \
              --build-arg BUILD_OTP_VERSION=<< parameters.otp_version >> - < << parameters.dockerfile >>
      - run:
          name: Push Docker image to docker.io registry
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push << pipeline.parameters.docker_repo >>:<< parameters.tag >>
      - when:
          condition: << parameters.latest >>
          steps:
            - run:
                name: Tag and push latest
                command: |
                  docker tag << pipeline.parameters.docker_repo >>:<< parameters.tag >> << pipeline.parameters.docker_repo >>:latest
                  docker push << pipeline.parameters.docker_repo >>:latest

  docker_manifest:
    parameters:
      manifest_list:
        type: string
      tag:
        type: string
    steps:
      - run:
          name: Create docker manifest
          command: |
            read -a MANIFEST_LIST_ARRAY \<<< "<< parameters.manifest_list >>"
            PREFIX="<< pipeline.parameters.docker_repo >>:"
            MANIFEST_LIST="${MANIFEST_LIST_ARRAY[@]/#/$PREFIX}"
            docker manifest create \
              << pipeline.parameters.docker_repo >>:<< parameters.tag >> \
              $MANIFEST_LIST
      - run:
          name: Login to docker.io registry
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push docker manifest
          command: |
            docker manifest push << pipeline.parameters.docker_repo >>:<< parameters.tag >>

jobs:
  build_and_push:
    executor: << parameters.platform >>
    parameters:
      platform:
        type: string
        default: amd64
      distro:
        type: string
      otp_version:
        type: string
      tag:
        type: string
      latest:
        type: boolean
        default: false
    steps:
      - checkout
      - build_and_push:
          dockerfile: Dockerfile-<< parameters.distro >>
          otp_version: << parameters.otp_version >>
          tag: << parameters.tag >>
          latest: << parameters.latest >>
  docker_manifest:
    executor: amd64
    parameters:
      manifest_list:
        type: string
      tag:
        type: string
    steps:
      - docker_manifest:
          manifest_list: << parameters.manifest_list >>
          tag: << parameters.tag >>

workflows:
  version: 2
  commit:
    jobs:
      - build_and_push:
          name: "build_2004_otp26_amd64"
          platform: amd64
          distro: "focal"
          otp_version: << pipeline.parameters.otp26 >>
          tag: ci-focal-otp26-amd64-<< pipeline.git.branch >>
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master

      - build_and_push:
          name: "build_2004_otp26_arm64"
          platform: arm64
          distro: "focal"
          otp_version: << pipeline.parameters.otp26 >>
          tag: ci-focal-otp26-arm64-<< pipeline.git.branch >>
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master

      - docker_manifest:
          name: "build_manifest_focal_otp26"
          manifest_list: >-
            ci-focal-otp26-amd64-<< pipeline.git.branch >>
            ci-focal-otp26-arm64-<< pipeline.git.branch >>
          tag: ci-focal-otp26-<< pipeline.git.branch >>
          context: ae-dockerhub
          requires:
            - build_2004_otp26_amd64
            - build_2004_otp26_arm64
          filters:
            branches:
              ignore: master

      - build_and_push:
          name: "build_2004_otp25_amd64"
          platform: amd64
          distro: "focal"
          otp_version: << pipeline.parameters.otp25 >>
          tag: ci-focal-otp25-amd64-<< pipeline.git.branch >>
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master

      - build_and_push:
          name: "build_2004_otp24_amd64"
          platform: amd64
          distro: "focal"
          otp_version: << pipeline.parameters.otp24 >>
          tag: ci-focal-otp24-amd64-<< pipeline.git.branch >>
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master

  release:
    jobs:
      - build_and_push:
          platform: amd64
          name: "release_2004_otp26_amd64"
          distro: "focal"
          otp_version: << pipeline.parameters.otp26 >>
          tag: "focal-otp26-amd64"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "release_2004_otp26_arm64"
          platform: arm64
          distro: "focal"
          otp_version: << pipeline.parameters.otp26 >>
          tag: "focal-otp26-arm64"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - docker_manifest:
          name: "release_manifest_bionic_otp26"
          manifest_list: >-
            focal-otp26-amd64
            focal-otp26-arm64
          tag: focal-otp26
          context: ae-dockerhub
          requires:
            - release_2004_otp26_amd64
            - release_2004_otp26_arm64
          filters:
            branches:
              only: master

      - docker_manifest:
          name: "release_manifest_latest"
          manifest_list: >-
            focal-otp26-amd64
            focal-otp26-arm64
          tag: latest
          context: ae-dockerhub
          requires:
            - release_2004_otp26_amd64
            - release_2004_otp26_arm64
          filters:
            branches:
              only: master

      - build_and_push:
          name: "release_2004_otp25"
          distro: "focal"
          otp_version: << pipeline.parameters.otp25 >>
          tag: "focal-otp25"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "release_2004_otp24"
          distro: "focal"
          otp_version: << pipeline.parameters.otp24 >>
          tag: "focal-otp24"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master
