version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:2021.02
    working_directory: ~/builder
    environment:
      DOCKERHUB_REPO: aeternity/builder
      DOCKER_CLIENT_VERSION: "17.09.0-ce"
      DOCKERFILE_PATH: "."

commands:
  use_remote_docker:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: "17.09.0-ce"
  build_and_push:
    parameters:
      dockerfile:
        type: string
      otp_version:
        type: string
      tag:
        type: string
    steps:
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_REPO:<< parameters.tag >> \
              --build-arg BUILD_OTP_VERSION=<< parameters.otp_version >> - < << parameters.dockerfile >>
      - run:
          name: Push Docker image to docker.io registry
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKERHUB_REPO:<< parameters.tag >>

jobs:
  build:
    executor: base
    steps:
      - checkout
      - use_remote_docker
      - build_and_push:
          dockerfile: Dockerfile-xenial
          otp_version: "22.3.4.9"
          tag: ci-xenial-otp22-<< pipeline.git.branch >>

  build_1604_otp21:
    executor: base
    steps:
      - checkout
      - use_remote_docker
      - build_and_push:
          dockerfile: Dockerfile-xenial
          otp_version: "21.3.8.17"
          tag: "xenial-otp21"

  build_1604_otp22:
    executor: base
    steps:
      - checkout
      - use_remote_docker
      - build_and_push:
          dockerfile: Dockerfile-xenial
          otp_version: "22.3.4.9"
          tag: "xenial-otp22"

  build_1604_otp23:
    executor: base
    steps:
      - checkout
      - use_remote_docker
      - build_and_push:
          dockerfile: Dockerfile-xenial
          otp_version: "23.3.4.5"
          tag: "xenial-otp23"

  build_1804_otp22:
    executor: base
    steps:
      - checkout
      - use_remote_docker
      - build_and_push:
          dockerfile: Dockerfile-bionic
          otp_version: "22.3.4.9"
          tag: "bionic-otp22"

  build_1804_otp23:
    executor: base
    steps:
      - checkout
      - use_remote_docker
      - build_and_push:
          dockerfile: Dockerfile-bionic
          otp_version: "23.3.4.5"
          tag: "bionic-otp23"

  build_1804_otp24:
    executor: base
    steps:
      - checkout
      - use_remote_docker
      - build_and_push:
          dockerfile: Dockerfile-bionic
          otp_version: "24.1.3"
          tag: "bionic-otp24"

  deploy:
    executor: base
    steps:
      - checkout
      - use_remote_docker
      - build_and_push:
          dockerfile: Dockerfile-xenial
          otp_version: "22.3.4.9"
          tag: latest

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master

      - build_1804_otp22:
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_1804_otp23:
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_1804_otp24:
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_1604_otp21:
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_1604_otp22:
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_1604_otp23:
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - deploy:
          context: ae-dockerhub
          filters:
            branches:
              only: master
