version: 2.1

parameters:
  buildx-version:
    type: string
    default: "0.7.0"

executors:
  base:
    docker:
      - image: cimg/base:stable-18.04
    working_directory: ~/builder
    environment:
      DOCKERHUB_REPO: aeternity/builder
      DOCKER_CLIENT_VERSION: "17.09.0-ce"
      DOCKERFILE_PATH: "."
  buildx:
    machine:
      image: ubuntu-2004:current
      resource_class: xlarge
    working_directory: ~/builder
    environment:
      DOCKERHUB_REPO: aeternity/builder
      DOCKER_CLIENT_VERSION: "20.10.11"
      DOCKERFILE_PATH: "."
      DOCKER_CLI_EXPERIMENTAL: "enabled"
      BUILDX_PLATFORMS: linux/amd64,linux/arm64

commands:
  use_remote_docker:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: "20.10.11"
  build_and_push:
    parameters:
      dockerfile:
        type: string
      otp_version:
        type: string
      tag:
        type: string
      latest:
        type: boolean
        default: false
    steps:
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_REPO:<< parameters.tag >> \
              --build-arg BUILD_OTP_VERSION=<< parameters.otp_version >> - < << parameters.dockerfile >>
      - run:
          name: Push Docker image to docker.io registry
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKERHUB_REPO:<< parameters.tag >>
      - when:
          condition: << parameters.latest >>
          steps:
            - run:
                name: Tag and push latest
                command: |
                  docker tag $DOCKERHUB_REPO:<< parameters.tag >> $DOCKERHUB_REPO:latest
                  docker push $DOCKERHUB_REPO:latest
  buildx_and_push:
    parameters:
      dockerfile:
        type: string
      otp_version:
        type: string
      tag:
        type: string
      latest:
        type: boolean
        default: false
    steps:
      - run:
          name: Install emulation dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y qemu binfmt-support qemu-user-static
      - run:
          name: Install buildx
          command: |
            mkdir -p ~/.docker/cli-plugins
            baseUrl="https://github.com/docker/buildx/releases/download"
            fileName="buildx-v<< pipeline.parameters.buildx-version >>.linux-amd64"
            url="${baseUrl}/v<< pipeline.parameters.buildx-version >>/${fileName}"
            curl -sSL -o ~/.docker/cli-plugins/docker-buildx $url
            chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run:
          name: Setup buildx
          command: |
            docker buildx install
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker run --rm --privileged tonistiigi/binfmt --install arm64
            docker context create aeternity_ctx
            docker context list
            docker buildx create --bootstrap --use --name aeternity_builder --platform $BUILDX_PLATFORMS aeternity_ctx
            docker buildx ls
            docker buildx inspect --builder aeternity_builder
      - run:
          name: Login to docker.io registry
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - unless:
          condition: << parameters.latest >>
          steps:
            - run:
                name: Build and push docker image to docker.io registry
                environment:
                  DOCKER_CLI_EXPERIMENTAL: enabled
                command: |
                  docker --context=aeternity_ctx buildx build --progress=plain --push \
                    -t $DOCKERHUB_REPO:<< parameters.tag >> \
                    --builder aeternity_builder \
                    --platform $BUILDX_PLATFORMS \
                    --build-arg BUILD_OTP_VERSION=<< parameters.otp_version >> \
                    - < << parameters.dockerfile >>
      - when:
          condition: << parameters.latest >>
          steps:
            - run:
                name: Build and push docker image to docker.io registry
                environment:
                  DOCKER_CLI_EXPERIMENTAL: enabled
                command: |
                  docker --context=aeternity_ctx buildx build --progress=plain --push \
                    -t $DOCKERHUB_REPO:<< parameters.tag >> \
                    -t $DOCKERHUB_REPO:latest \
                    --builder aeternity_builder \
                    --platform $BUILDX_PLATFORMS \
                    --build-arg BUILD_OTP_VERSION=<< parameters.otp_version >> \
                    - < << parameters.dockerfile >>

jobs:
  build_and_push:
    executor: base
    parameters:
      distro:
        type: string
      otp_version:
        type: string
      tag:
        type: string
        default: bionic-otp22
      latest:
        type: boolean
        default: false
    steps:
      - checkout
      - use_remote_docker
      - build_and_push:
          dockerfile: Dockerfile-<< parameters.distro >>
          otp_version: << parameters.otp_version >>
          tag: << parameters.tag >>
          latest: << parameters.latest >>
  buildx_and_push:
    executor: buildx
    parameters:
      distro:
        type: string
      otp_version:
        type: string
      tag:
        type: string
        default: bionic-otp22
      latest:
        type: boolean
        default: false
    steps:
      - checkout
      - buildx_and_push:
          dockerfile: Dockerfile-<< parameters.distro >>
          otp_version: << parameters.otp_version >>
          tag: << parameters.tag >>
          latest: << parameters.latest >>

workflows:
  version: 2
  commit:
    jobs:
      - buildx_and_push:
          name: "build_1804_otp22"
          distro: "bionic"
          otp_version: "22.3.4.9"
          tag: ci-bionic-otp22-<< pipeline.git.branch >>
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master
      - build_and_push:
          name: "build_2004_otp22"
          distro: "focal"
          otp_version: "22.3.4.9"
          tag: ci-focal-otp22-<< pipeline.git.branch >>
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master

  release:
    jobs:
      - buildx_and_push:
          name: "build_1804_otp22"
          distro: "bionic"
          otp_version: "22.3.4.9"
          tag: "bionic-otp22"
          latest: true
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_1804_otp23"
          distro: "bionic"
          otp_version: "23.3.4.5"
          tag: "bionic-otp23"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_1804_otp24"
          distro: "bionic"
          otp_version: "24.1.3"
          tag: "bionic-otp24"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_2004_otp22"
          distro: "focal"
          otp_version: "22.3.4.9"
          tag: "focal-otp22"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_2004_otp23"
          distro: "focal"
          otp_version: "23.3.4.5"
          tag: "focal-otp23"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_2004_otp24"
          distro: "focal"
          otp_version: "24.1.3"
          tag: "focal-otp24"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master
