version: 2.1

parameters:
  buildx-version:
    type: string
    default: "0.10.0"
  docker_repo:
    type: string
    default: aeternity/aeternity
  buildx_platforms:
    type: string
    default: linux/arm64,linux/amd64

executors:
  base:
    docker:
      - image: cimg/base:stable-18.04
    working_directory: ~/builder
  buildx:
    docker:
      - image: cimg/base:stable
    resource_class: xlarge
    working_directory: /home/circleci/aeternity

commands:
  use_remote_docker:
    steps:
      - setup_remote_docker:
          # docker_layer_caching: true
          version: "20.10.18"
  build_and_push:
    parameters:
      dockerfile:
        type: string
      otp_version:
        type: string
      tag:
        type: string
      latest:
        type: boolean
        default: false
    steps:
      - run:
          name: Build Docker image
          command: |
            docker build -t << pipeline.parameters.docker_repo >>:<< parameters.tag >> \
              --build-arg BUILD_OTP_VERSION=<< parameters.otp_version >> - < << parameters.dockerfile >>
      - run:
          name: Push Docker image to docker.io registry
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push << pipeline.parameters.docker_repo >>:<< parameters.tag >>
      - when:
          condition: << parameters.latest >>
          steps:
            - run:
                name: Tag and push latest
                command: |
                  docker tag << pipeline.parameters.docker_repo >>:<< parameters.tag >> << pipeline.parameters.docker_repo >>:latest
                  docker push << pipeline.parameters.docker_repo >>:latest
  buildx_and_push:
    parameters:
      dockerfile:
        type: string
      otp_version:
        type: string
      tag:
        type: string
      latest:
        type: boolean
        default: false
    steps:
      - run:
          name: Login to docker.io registry
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - unless:
          condition: << parameters.latest >>
          steps:
            - run:
                name: Build and push docker image to docker.io registry
                command: |
                  docker buildx build --progress=plain --push \
                    -t << pipeline.parameters.docker_repo >>:<< parameters.tag >> \
                    --platform << pipeline.parameters.buildx_platforms >> \
                    --build-arg BUILD_OTP_VERSION=<< parameters.otp_version >> \
                    - < << parameters.dockerfile >>
      - when:
          condition: << parameters.latest >>
          steps:
            - run:
                name: Build and push docker image to docker.io registry
                command: |
                  docker buildx build --progress=plain --push \
                    -t << pipeline.parameters.docker_repo >>:<< parameters.tag >> \
                    -t << pipeline.parameters.docker_repo >>:latest \
                    --platform << pipeline.parameters.buildx_platforms >> \
                    --build-arg BUILD_OTP_VERSION=<< parameters.otp_version >> \
                    - < << parameters.dockerfile >>

jobs:
  build_and_push:
    executor: base
    parameters:
      distro:
        type: string
      otp_version:
        type: string
      tag:
        type: string
        default: bionic-otp23
      latest:
        type: boolean
        default: false
    steps:
      - checkout
      - use_remote_docker
      - build_and_push:
          dockerfile: Dockerfile-<< parameters.distro >>
          otp_version: << parameters.otp_version >>
          tag: << parameters.tag >>
          latest: << parameters.latest >>
  buildx_and_push:
    executor: buildx
    parameters:
      distro:
        type: string
      otp_version:
        type: string
      tag:
        type: string
        default: bionic-otp23
      latest:
        type: boolean
        default: false
    steps:
      - checkout
      - buildx_and_push:
          dockerfile: Dockerfile-<< parameters.distro >>
          otp_version: << parameters.otp_version >>
          tag: << parameters.tag >>
          latest: << parameters.latest >>

workflows:
  version: 2
  commit:
    jobs:
      - buildx_and_push:
          name: "build_1804_otp23"
          distro: "bionic"
          otp_version: "23.3.4.5"
          tag: ci-bionic-otp23-<< pipeline.git.branch >>
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master
      - build_and_push:
          name: "build_2004_otp23"
          distro: "focal"
          otp_version: "23.3.4.5"
          tag: ci-focal-otp23-<< pipeline.git.branch >>
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              ignore: master

  release:
    jobs:
      - build_and_push:
          name: "build_1804_otp23"
          distro: "bionic"
          otp_version: "23.3.4.5"
          tag: "bionic-otp23"
          latest: true
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_1804_otp24"
          distro: "bionic"
          otp_version: "24.1.3"
          tag: "bionic-otp24"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_2004_otp23"
          distro: "focal"
          otp_version: "23.3.4.5"
          tag: "focal-otp23"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master

      - build_and_push:
          name: "build_2004_otp24"
          distro: "focal"
          otp_version: "24.1.3"
          tag: "focal-otp24"
          context: ae-dockerhub
          requires: []
          filters:
            branches:
              only: master
